default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  port: 5432
  pool: <%= ENV["RAILS_MAX_THREADS"] { 5 } %>

development:
  <<: *default
  database: auth_sandbox_development
  password: 'postgres'
  host: postgres_db

# staging:
#   <<: *default
#   database: <%= Rails.application.credentials.dig(:db, :name) %>_staging
#   password: <%= Rails.application.credentials.dig(:db, :password) %>
#   host: <%= Rails.application.credentials.dig(:db, :host) %>

test:
  <<: *default
  database: auth_sandbox_test
  password: 'postgres'
  host: postgres_db

# production:
#   <<: *default
#   database: <%= Rails.application.credentials.dig(:db, :name) %>_production
#   password: <%= Rails.application.credentials.dig(:db, :password) %>
#   host: <%= Rails.application.credentials.dig(:db, :host) %>
